### ISSUE TITLE
Ipv6 not working... 

### ISSUE THREAD

**Issue by FilipeBorges1993** [JiaJiaJiang/node-socks5server#1] opened 2021-12-29 16:42 UTC
When i try to use some ipv6 Dns (like www.youtube.com) i get and empty string as $address ...

**Comment by JiaJiaJiang** [comment] 2021-12-29 17:05
How did you use it? I passed an ipv6 test just now, did you use it as a module or just started the proxy.js?

**Comment by FilipeBorges1993** [comment] 2021-12-29 18:53
As a module, but keep getting '' when try to resolve Youtube.com url to ipv6... totally empty .... I even analyse your '[...buffer.slice(buffer[offset+1], buffer[offset+1]+16)].map(num=>num.toString(16)).join(':');' and even here i get an empty string ... What version of node are you using ?!

**Comment by JiaJiaJiang** [comment] 2021-12-30 01:51
I'm using v16+, but this module was done long long ago, it should be OK in several earlier versions, can you try starting a `node proxy.js -P 1080` instance for testing if it's a vesion problem?

**Comment by FilipeBorges1993** [comment] 2021-12-30 12:39
I test it and i got the same result ...

**Comment by JiaJiaJiang** [comment] 2021-12-30 13:11
> As a module, but keep getting '' when try to resolve Youtube.com url to ipv6... totally empty .... I even analyse your '[...buffer.slice(buffer[offset+1], buffer[offset+1]+16)].map(num=>num.toString(16)).join(':');' and even here i get an empty string ... What version of node are you using ?!

Since I cannot reproduce this bug, may you print `buffer` and `buffer.slice(buffer[offset+1], buffer[offset+1]+16)` before the `return` line to watch what's in the buffer?
By the way, what's your socks5 client? Is that a web browser or a script by yourself? If it's a web browser, the browser should send a socks5 request with `ATYP(Address type)` as 'DNS', and this request's target address will be read as a domain string but not an ipv6 address.

**Comment by FilipeBorges1993** [comment] 2021-12-30 14:19
Can you add me on discord ?! FilipeBorges#0250, i'm using fireFox as client

**Comment by JiaJiaJiang** [comment] 2021-12-30 14:39
Sorry, I dont have a discord  account. 
I tested it on chrome before, now I have reproduced it on firefox, leave me some time for it.

**Comment by JiaJiaJiang** [comment] 2021-12-30 15:07
Ha Ha, I made a stupid mistake when reconstructed the code to new ES grammar, now it should be fixed.
I have commit it to master and publish a new version 4.4.2 on npm, have a try!

**Closed as completed** 2022-01-02 04:43 UTC
Labels: bug
